version: "3.9" # optional since v1.27.0
services:
  auth-node:
    image: rootberg/auth-service:latest
    environment:
      DATABASE_URL: ${DATABASE_URL}
      TOKEN_SECRET: ${TOKEN_SECRET}
    ports:
      - "5000:5000"
    links:
      - db
    depends_on:
      - db
  db:
    image: registry.digitalocean.com/rootberg/user-db:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5555"
