version: "3.9" # optional since v1.27.0
services:
  auth-node:
    build: .
    command: yarn start
    environment:
      DATABASE_URL: ${DATABASE_URL}
      TOKEN_SECRET: ${TOKEN_SECRET}
    ports:
      - "5000:5000"
    links:
      - db
  db:
    image: rootberg/user-db:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: userdb
    ports:
      - "5432:5555"
